apiVersion: v1
kind: Service
metadata:
  name: demo-microservice-service
spec:
  selector:
    app: demo-microservice
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32003
